### ISSUE TITLE
Developer Money should not be empty

### ISSUE THREAD

**Issue by rafsanrana** [dipta007/money-management-freelancers#13]
Developer money should not be empty

**Comment by dipta007** [comment]
Is it possible to make it empty and then submit?

**Comment by rafsanrana** [comment]
I think no. But what if we don't pay any developers ? Like someone do the job for free. So, there should be an option to input "0" as developer money. But I don't what happened in database if I input empty as developer money. If it is converted in "0" than it's ok.

**Comment by dipta007** [comment]
put 0 in that case

**Comment by rafsanrana** [comment]
Fine then. (y)
